### ISSUE TITLE
ViT training

### ISSUE THREAD

**Issue by j-cb** [plantnet/PlantNet-300K#2]
As far as I can see, the code for training the Vision Transformer which is evaluated in the paper is not included.

Could you state or link the training details for the evaluated ViT?

Was it trained from scratch, or did you fine-tune a pre-trained model?

Best,
Julian

**Comment by garcinc** [comment]
Hello Julian,

The model used was pre-trained on ImageNet. The hyperparameters specific to ViT can be found in section B of the supplementary material (available here : https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/hash/7e7757b1e12abcb736ab9a754ffb617a-Abstract-round2.html)

Best,
Camille
