### ISSUE TITLE
main.py - train error - Anaconda Windows 10 - gpu

### ISSUE THREAD

**Issue by steppige** [plantnet/PlantNet-300K#3]
I tried to insert the string ...
`python main.py --lr=0.05 --n_epochs=80 --k 1 3 5 10 --model=resnet50 --root=C:\Users\steppi\PlantNet-300K --save_name_xp=xp1`

But I am getting this error on Windows PC - nvidia cuda GPU.

`(Pytorch) C:\Users\steppi\PlantNet-300K>python main.py --lr=0.05 --n_epochs=80 --k 1 3 5 10 --model=resnet50 --root=C:\Users\steppi\PlantNet-300K --save_name_xp=xp1                                                                            Seed:    None                                                                                                           Traceback (most recent call last):                                                                                        File "main.py", line 102, in <module>                                                                                     train(args)                                                                                                           File "main.py", line 16, in train                                                                                         set_seed(args, use_gpu=torch.cuda.is_available())                                                                     File "C:\Users\steppi\PlantNet-300K\utils.py", line 21, in set_seed                                                       torch.manual_seed(args.seed)                                                                                          File "C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\random.py", line 36, in manual_seed                   seed = int(seed)                                                                                                    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'           `

What am I doing wrong? I left the main.py file unchanged

**Comment by garcinc** [comment]
Hi,

You should try to add the seed argument to your command line: --seed=8

Bests,
