### ISSUE TITLE
from species_id to name of plant?

### ISSUE THREAD

**Issue by huytuong010101** [plantnet/PlantNet-300K#4]
Hi bro,
Thank you for perfect dataset but can you tell me how to get the name of plant by the species_id in your dataset?
Thank u so much <3

**Comment by maximiliense** [comment]
Hi,

The file plantnet300K_species_names.json maps the species_id to the corresponding name.

**Comment by huytuong010101** [comment]
Thank for your reply
But a cannot find the `plantnet300K_species_names.json` in dataset, just ` plantnet300K_metadata.json` :(

**Comment by huytuong010101** [comment]
Ah yesss, I see it, thank you so much,
I have one more isssue: The paper show that `It is organized in three folders named “train”, “val” and “test”`
But i just see the **train** at `https://zenodo.org/record/4726653` and the **test** folder at  `https://zenodo.org/record/5645731`
Where can i find **val** folder?

**Comment by huytuong010101** [comment]
Thank u so much <3
