### ISSUE TITLE
Lien neurips down

### ISSUE THREAD

**Issue by alexisjoly** [plantnet/PlantNet-300K#5]
Lien neurips marche plus:
https://datasets-benchmarks-proceedings.neurips.cc/paper/2021/file/7e7757b1e12abcb736ab9a754ffb617a-Paper-round2.pdf

**Comment by AntoineAA** [comment]
This is a 500 error, hopefully it will be fixed soon.
The Website seems to be down: https://datasets-benchmarks-proceedings.neurips.cc/
